### ISSUE TITLE
Doesn't show any tags or revisions

### ISSUE THREAD

**Issue by smerrill** [lukanus/git-parameter#2]
Here's my setup:

CentOS 6
Tomcat6 installed via yum
git 1.7.1 installed via yum
Jenkins v1.444 running under tomcat6
git-parameter 0.1

I have a project checked out from github over ssh using the git plugin. The project has 1 tag and many revisions, but when I create a git parameter that lists either tags or revisions, the parameter comes up blank.

![D'oh](https://img.skitch.com/20111222-jmafcdihqfsja33smdqsaw7y4c.jpg)

Any ideas?

**Comment by lukanus** [comment]
Yeah, You have the latest version of jenkins probably with the latest update of git plugin on which is git-parameter based. 
I don't really know what had changed in this libs, but it does stop working for me also.
Now I have pretty hot time at my work, but I'll try to put it all together until the end of this year, along with some features, probably supporting branches and slave/master configuration. Speaking of which, any feedback, what functionalities you would wanted to have along with this plugin will be appreciated.  
Cheers

**Comment by smerrill** [comment]
Honestly, just being able to pick from a list of tags would be great. I usually put a parameter into a job to specify which tag to deploy.

**Comment by haysclark** [comment]
+1 for fix.  I would love for this plug-in to work again. Doesn't work on any of the 1.4x versions I guess. Any updates?  I only am interested in Tag support right now.

**Comment by lukanus** [comment]
ok... so.... sorry for delay, I am pretty busy lately.  
It stops working along with the addition of 'reference' parameter to main GitApi() constructor from git plugin. For me now it is fixed but I'm not going to close this issue now, I will wait a little bit, for any feedback from You if everything is ok. 
Along with this you can now pick from which branch you want to choose tags/revisions.

**Comment by playupchris** [comment]
It works for me in v0.2, although I had to first build with no tag parameter (so it would check out the code - to get the tags in the first place).

The only disappointing thing is that it doesn't sort the tags (ideally in such a way that "tag_2" comes before "tag_12", but even sorting them alphabetically would make it more useable).

**Comment by cmeffngmoco** [comment]
I am experiencing this issue with Jenkins v 1.477 and git parameter v 0.2

**Comment by franck-grenier** [comment]
Hello,
it's impossible for me to get Git tags list.
I'm using Jenkins 1.432 and git parameter v 0.2.

I've tried to build the job first without Git parameter in order to clone the repo. But the git-parameter tag list is always empty.

**Comment by bobashforth** [comment]
It's now July 11 2013; I've just installed this plugin and am seeing an empty tag list. Has there been any work/progress on this issue?

**Comment by troelsselch** [comment]
Still no news on this? I'm having the same problem. (November 28 2013)
Setup:
OS: Ubuntu Precise
Jenkins 1.541
Git Parameter plugin 0.2
Git Client plugin 1.4.5
Git plugin 2.0
Git version  1.7.9.5

**Comment by clarson99** [comment]
Are there any plans to fix this, or is this a dead project?

**Comment by sethfloydjr** [comment]
For me I ran a build from my master branch. Then went back into the job and added the git-parameter options and then I could see my tags in the dropdown.
I noticed this line on the Git-Parameters plugin main page: 
https://wiki.jenkins-ci.org/display/JENKINS/Git+Parameter+Plugin

"There is a problem when you want to build your project for a first time and you don't have any suitable workspace which works with git, then the list to chose from is empty, but it will work after the first build"

Unfortunately the way we build is based on tags so we have hundreds and the drop down doesnt sort them which is a HUGE pain. I saw a pull request here but it doesnt look like its been merged in and released for some reason.
https://github.com/jenkinsci/git-parameter-plugin/pull/1

**Comment by lukanus** [comment]
Hi! I'm not able to test this in production env. now.  
If you gave me green light, that it (any pull request) is working against lastest jenkins version, I'll merge this.
And that way, untill I will once again have some time to setup whole dev env for that.

**Comment by ngiger** [comment]
See version 0.3.2 under https://wiki.jenkins-ci.org/display/JENKINS/Git+Parameter+Plugin.
Can you close this issue as I have no committer right here? Thanks in advance.

**Comment by TJM** [comment]
We still don't see any tags listed (I even tried revisions, nothing)...

Our Specs:
- OS: Cent OS 6.5
- Jenkins 1.554.2 (stable)
- git parameter plugin 0.3.2
- GIT plugin 2.2.1
- GIT Client Plugin 1.9.1
- Local git version 1.7.1

There is no output in the build window to indicate that it is even trying :-/

However, git ls-remote / git tag works:

```
$ git ls-remote -t git@gitserver:reponame 
df98b191dcd34cf3b6f7aa2469c93e83753c5bc7    refs/tags/v1.0
190f945204323e63bdd908061d71358a285c7c66    refs/tags/v1.0^{}

$ git tag -l
v1.0
```

Any tips? I don't know where to start debugging ~~because I see no errors~~ ;)

Oh, wait, maybe this NPE sheds light on it?

https://github.com/jenkinsci/git-parameter-plugin/blob/git-parameter-0.3.2/src/main/java/net/uaznia/lukanus/hudson/plugins/gitparameter/GitParameterDefinition.java#L260

```
Jun 17, 2014 10:09:40 AM hudson.ExpressionFactory2$JexlExpression evaluate
WARNING: Caught exception evaluating: it.revisionMap in /job/SF-Dev/job/Deploy-Auction-GitTag/build. Reason: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
((SNIP))
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NullPointerException
    at net.uaznia.lukanus.hudson.plugins.gitparameter.GitParameterDefinition.generateContents(GitParameterDefinition.java:260)
    at net.uaznia.lukanus.hudson.plugins.gitparameter.GitParameterDefinition.getRevisionMap(GitParameterDefinition.java:386)
    ... 167 more

```

**Comment by TJM** [comment]
I am betting that the problem is somewhere in here: https://github.com/jenkinsci/git-parameter-plugin/blob/git-parameter-0.3.2/src/main/java/net/uaznia/lukanus/hudson/plugins/gitparameter/GitParameterDefinition.java#L184-L213

context is set to null, then there is some sort of elaborate sequence that _should_ set context to the project during the loop, but apparently that is not happening.

**Comment by TJM** [comment]
For my issue, I filed https://issues.jenkins-ci.org/browse/JENKINS-23473

**Comment by GregOriol** [comment]
It seems that this issue is still happening here, any news on it?

**Comment by sas05** [comment]
I have also got this problem.

**Comment by dariogriffo** [comment]
Same problem here, no way to make it work, I tried changing branches, nothing...
